name: hello-world
run-name: Hola mundo, desde un script de ruby
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
      - run: ruby hello_world.rb
