name: Saludo usando variables
run-name: ¡Estoy aprendiendo a usar Variables!
on: [push]
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO, $NOMBRE. Hoy es $DIA_DE_SEMANA!"
        env:
          NOMBRE: Juan
      - name: Obtener secret
        run: |
          echo "Mi secreto es ${{ secrets.MY_SECRET }}"
      - name: Obtener env var
        run: echo "Mi variable de entorno es ${{ vars.MY_VAR }}"